apiVersion: v1
kind: ServiceAccount
metadata:
  name: authlab
  namespace: authlab
  labels:
    app.kubernetes.io/name: authlab
    app.kubernetes.io/part-of: secure-deploy-lab
    app.kubernetes.io/component: web
    app.kubernetes.io/managed-by: kubectl
automountServiceAccountToken: false